name: Tests
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@master
      - name: Test
        run: |
          pip install pytest coverage pytest-cov
          pip install -r requirements.txt
          python -m pytest --verbose --disable-pytest-warnings --cov=GibbsSampler --cov-report=xml
      - name: Upload
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
