name: Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install pytest coverage pytest-cov pytest-xdist
          pip install -r requirements.txt
      - name: Fetch
        uses: actions/checkout@master
      - name: Test
        run: |
          python -m pytest --verbose --disable-pytest-warnings --cov=baypy --cov-report=xml -nauto
      - name: Upload
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
